# Software 
source /sw/batch/init.sh
module load apptainer
module load parallel

# Environment variables
export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"  # Script localization
export CODE_DIR=$SCRIPT_DIR                                                         # Code directory
export PROJ_DIR=$(realpath $SCRIPT_DIR/..)                                          # Project root; should be 1 level above $SCRIPT_DIR
export ENV_DIR=$PROJ_DIR/envs                                                       # Software environments directory
export PIPELINE_DIR=$CODE_DIR/pipelines/$PIPELINE                                   # Pipeline-specific subdirectory in $CODE_DIR 
export DATA_DIR=$PROJ_DIR/data                                                      # Data directory inputs come from and outputs go to; should 
export DCM_DIR=$PROJ_DIR/data/dicoms                                                # Raw inputs dicom
export BIDS_DIR=$PROJ_DIR/data/raw_bids                                             # Raw inputs bids
export SCRATCH_DIR=$RRZ_LOCAL_TMPDIR                                                # Directory for intermediate files; should be writable and ideally fast
export HPC_NTHREADS=8                                                               # Threads per virtual node
export HPC_MEM=32000                                                                # Memory per virtual node
export DERIVATIVE_DIR=$DATA_DIR/$PIPELINE/derivatives

